# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20170311_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
