# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20170311_0619'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
